server:
  port: 8083

spring:
  application:
    name: external-banking-service
  datasource:
    url: jdbc:h2:mem:external-banking;MODE=MySQL
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

mock:
  accounts:
    - accountNumber: "2000-0000-0001"
      holderName: "고범석"
    - accountNumber: "2000-0000-0002"
      holderName: "짱구"
    - accountNumber: "2000-0000-0003"
      holderName: "맹구"